### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by joesen-dev** [leunggerry/personal-health-tracker#41]
- [x] Project decided
- [x] React Router page structure created
- [x] GraphQL typeDefs and resolvers defined
- [x] Service worker added
- [x] Web manifest created
- [ ] Offline functionality complete
- [x] Authentication created
- [ ] Testing
- [ ] Documentation created
- [x] Presentation created
